stages:
  training:
    cmd: python notebooks/stressModel.py
    outs:
    - models/best_model.h5
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  best_model:
    path: models/best_model.h5
    type: model
    desc: This is a convolutional neural network model that is developed to detect
      stress.
    labels:
    - no-stress
    - stress
params:
- dvclive/params.yaml
