name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt black[jupyter] jupyter nbconvert
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        id: action_black
        with: 
          options: "--verbose"
          src: "./code"
          jupyter: true

  DVC-CML-Pipeline:
    runs-on: [ubuntu-latest]
    env:
      REPO_TOKEN: ${{ secrets.TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: List contents of data directory
      run: ls -l data
    
    - name: Install DVC
      uses: iterative/setup-dvc@v1
    
    - name: Install CML
      uses: iterative/setup-cml@v2
      
    - name: Set-up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Train and Evaluate
      run: |
        dvc repro dvc.yaml
        dvc metrics diff --md > metrics.md
        dvc params diff --md > params.md

    - name: Generate Report
      run: |          
        git fetch --prune
        dvc metrics diff --md main > report.md
        cml comment create report.md  
