name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt black[jupyter] jupyter nbconvert
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        id: action_black
        with: 
          options: "--verbose"
          src: "./code"
          jupyter: true

  DVC-CML-Pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install DVC
      uses: iterative/setup-dvc@v1
      
    - name: Install CML
      uses: iterative/setup-cml@v2
     
    - name: List contents of data directory
      run: ls -l data

    - name: List contents of code directory
      run: ls -l notebooks
    
    - name: Train model
      env:
        AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        pip install -r requirements.txt  # Install dependencies
        dvc pull data --run-cache        # Pull data & run-cache from Azure Blob Storage
        dvc repro                        # Reproduce pipeline                    

    - name: Create CML Report
      env:
        REPO_TOKEN: ${{ secrets.TOKEN }}
      run: |         
        echo "## Metrics: workflow vs. main" >> report.md
        git fetch --depth=1 origin main:main 

        dvc metrics diff --md main > report.md
        cml comment create report.md  
