name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      merged_data: ${{ steps.extract.outputs.merged_data }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt black[jupyter] jupyter nbconvert
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        id: action_black
        with: 
          options: "--verbose"
          src: "./code"
          jupyter: true

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
     # may need to setup NodeJS & Python3 on e.g. self-hosted
     # - uses: actions/setup-node@v3
     #   with:
     #     node-version: '16'
     # - uses: actions/setup-python@v4
     #   with:
     #     python-version: '3.x'
    - name: List contents of data directory
      run: ls -l data
    
    - uses: iterative/setup-cml@v2
    - name: Write CML report
      env:
        REPO_TOKEN: ${{ secrets.TOKEN }}
      run: |
        # Your ML workflow goes here
        pip install -r requirements.txt
        python code/eda_signal_classification.py
        
        # Post CML report as a comment in GitHub
        echo "## Model Metrics" > report.md
        cat code/metrics.txt >> report.md

        echo "\n## Model Performance" >> report.md
        echo "Model performance metrics are on the plot below." >> report.md
        echo '![](code/model_results.png)' >> report.md

        cml comment create --publish report.md        