name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      merged_data: ${{ steps.extract.outputs.merged_data }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt



  data:
    runs-on: ubuntu-latest
    steps:
      - name: Create data directory
        run: mkdir -p data

      - name: Download dataset
        run: |
          curl -L -o data/dataset.zip https://uni-siegen.sciebo.de/s/HGdUkoNlW1Ub0Gx/download
          if file data/dataset.zip | grep -q 'Zip archive data'; then
            echo "Valid ZIP file."
          else
            echo "Invalid ZIP file. Exiting."
            exit 1
          fi

      - name: Extract files
        id: extract
        run: |
          # Run the extraction process here and output the merged_data.csv
          1. unzip_script.ipynb
          echo "::set-output name=merged_data::merged_data.csv"

  run:
    needs: [build, data]
    runs-on: ubuntu-latest
    steps:
      - name: Run Jupyter notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to script eda_signal_classification.ipynb
          python eda_signal_classification.py

  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbstripout flake8
    
      - name: Lint Python Code
        run: |
          find . -name '*.ipynb' -type f -exec bash -c 'flake8 --ignore=E,W,N {}' \;

  changelog:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get changelog diff
        run: |
          pip install nbconvert
          jupyter nbconvert --to script eda_signal_classification.ipynb
          python eda_signal_classification.py

      - name: Jupyter Notebooks to PDF
        run: |
          pip install nbconvert
          jupyter nbconvert --to script eda_signal_classification.ipynb
          python eda_signal_classification.py
