name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt

  data:
    runs-on: ubuntu-latest
    steps:
      - name: Create data directory
        run: mkdir -p data

      - name: Download dataset
        run: |
          curl -L -o data/dataset.zip https://uni-siegen.sciebo.de/s/HGdUkoNlW1Ub0Gx/download
          if file data/dataset.zip | grep -q 'Zip archive data'; then
            echo "Valid ZIP file."
          else
            echo "Invalid ZIP file. Exiting."
            exit 1
          fi

      - name: Unzip dataset
        run: unzip data/dataset.zip -d data

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Jupyter notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to script eda_signal_classification.ipynb
          python eda_signal_classification.py

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
        with:
          paths: '**/*.ipynb'

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Get changelog diff
        uses: jupyter-naas/get-changelog-diff@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Jupyter Notebooks to PDF
        uses: MohamedElash
