name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      merged_data: ${{ steps.extract.outputs.merged_data }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt black[jupyter] jupyter nbconvert



  # run:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Create data directory
  #       run: mkdir -p data

  #     - name: Download dataset
  #       run: |
  #         curl -L -o data/WESAD.zip https://uni-siegen.sciebo.de/s/HGdUkoNlW1Ub0Gx/download
  #         if file data/WESAD.zip | grep -q 'Zip archive data'; then
  #           echo "Valid ZIP file."
  #         else
  #           echo "Invalid ZIP file. Exiting."
  #           exit 1
  #         fi

  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements.txt

  #     - name: Print Working Directory
  #       run: pwd
        
  #     - name: Convert notebook to script
  #       run: |
  #         jupyter nbconvert --to script code/eda_signal_classification.ipynb
  #         python code/eda_signal_classification.py

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        id: action_black
        with: 
          options: "--verbose"
          src: "./code"
          jupyter: true



  run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn matplotlib seaborn keras numpy tensorflow cvxopt
        
    - name: Run model
      run: python code/eda_signal_classification.py
        
    - name: Upload confusion matrix
      uses: actions/upload-artifact@v2
      with:
        name: confusion-matrix
        path: confusion_matrix.png
        
    - name: Upload accuracy score
      uses: actions/upload-artifact@v2
      with:
        name: accuracy-score
        path: accuracy_score.txt