name: Deploy Model via Docker

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build-and-publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up DVC
        run: |
          pip install dvc[azure]  # Replace `[azure]` with your DVC remote type
          dvc pull models --run-cache  # Pull the model from the DVC remote
          ls -al  # List files to confirm the model is downloaded

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker-compose -f ./docker-compose.yml build

      - name: Tag Docker Image
        run: |
          docker tag $(docker images -q masterofappliedit) ghcr.io/${{ github.repository_owner }}/masterofappliedit:latest

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/masterofappliedit:latest
