name: Publish Docker Image to GHCR

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  pull_request:
    branches:
      - main
      
      
jobs:
  build-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker Image
        run: |
          docker-compose build

      - name: Tag Docker Image
        run: |
          docker tag masterofappliedit ghcr.io/${{ github.repository_owner }}/masterofappliedit:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/masterofappliedit:latest
